remote_theme: jekyll-theme-plain/jekyll-theme-plain

# lang: en
# color_scheme: false # disables sync with system theme
title: Your awesome title
# url: https://YOURDOMAIN.com
# basename: 
# canonical_url: false # disables canonical URLs
# license_url: 

# To use a style sheet, place it in _includes/XXX.css and uncomment the following lines:
# stylesheets:
#   - XXX.css
